### ISSUE TITLE
Cannot resolve symbol 'envInjectBuilder'

### ISSUE THREAD

**Issue by iRobertas** [cfpb/jenkins-as-code-starter-project#9]
Hello, I'm trying to use your starter project and have some problems with my configs.
When I run gradlew rest -Dpattern=jobs/** -DbaseUrl=http://localhost:8080 -Dusername=foo -Dpassword=bar, example jobs are created/updated
Hello-Pipeline-Job - updated
Hello-Freestyle-Job - updated
But my job throws error  Caused by: groovy.lang.MissingMethodException: No signature of method: javaposse.jobdsl.dsl.helpers.step.StepContext.envInjectBuilder() is applicable for argument types: (script$_run_closure1$_closure8$_closure20) values: [script$_run_closure1$_closure8$_closur
e20@2e11485]
I use Environment Injector Plugin which provides envInjectBuilder, in my configs envInjectBuilder is grey, on mouseover shows "Cannot resolve symbol 'envInjectBuilder'" but idea autocompletion works.
How can I fix this ?

**Comment by marcesher** [comment]
@iRobertas A few questions:

1. Do both jobs throw that error?
2. What version of jenkins, what version of job-dsl, and what version of EnvInject are you using in that local Jenkins?

Finally, please provide the entire contents of the console output for a failed job. Thanks.

**Comment by marcesher** [comment]
Actually, on second thought, I'm confused. At first I thought you meant that when you ran the job in Jenkins, it would fail with that `MissingMethodException`, but that doesn't make any sense to me since once a job has been created, there's no `jobdsl` bits in it and so that error doesn't seem to relate to the running of the job in Jenkins. 

Please clarify exactly where/how this error is occurring. Thanks.

**Comment by iRobertas** [comment]
Jenkins 2.127
Environment Injector Plugin 2.1.5
Job DSL 1.69

Errors are thrown when I execute gradlew rest command (job creation process), not when I run job on jenkins. 

I execute command "gradlew rest -Dpattern=jobs/** -DbaseUrl=http://localhost:8080 -Dusername=foo -Dpassword=bar" in IntelliJ terminal.
Both example jobs Hello-Pipeline-Job and Hello-Freestyle-Job successfully created on my local jenkins but my  job creation fails with error (output.txt). I tried to comment out envInjectBuilder part and then job is created without errors.

[output.txt](https://github.com/cfpb/jenkins-as-code-starter-project/files/2093174/output.txt)

**Comment by marcesher** [comment]
@iRobertas thanks for the details; they're very helpful.

I see from the output that it's failing on a file called myJob.groovy:

```
processing file: E:\jenkins-wip\jobs\myJob.groovy
Processing provided DSL script
Exception in thread "main" javaposse.jobdsl.dsl.DslScriptException: (script, line 85) No signature of method: javaposse.jobdsl.dsl.helpers.step.StepContext.envInjectBuilder() is applicable for argument types: (script$_run_closure1$_closure8$_closure20) values:
[script$_run_closure1$_closure8$_closure20@a8e6492]
```

What is that `myJob.groovy` file? Is that something you created? If so, please post the contents so we can help.

**Comment by iRobertas** [comment]
Yes, I added this file.
[myJob.txt](https://github.com/cfpb/jenkins-as-code-starter-project/files/2098297/myJob.txt)

**Comment by marcesher** [comment]
@iRobertas Thanks, that is very helpful.

OK, what's going on here is that `envInjectBuilder` is part of the [dynamically generated DSL](https://github.com/jenkinsci/job-dsl-plugin/wiki/Dynamic-DSL). Unfortunately, the `rest` runner does not work with dynamically generated DSL, per https://github.com/sheehan/job-dsl-rest-example#rest-api-runner. This is one of the limitations of the `rest` runner, and I do not currently know if any workaround. For our part, when we have dsl scripts that use generated DSL, we do not run them with the `rest` runner.

If you set up a seed job (see https://github.com/jenkinsci/job-dsl-plugin/wiki) that runs your job within Jenkins itself, it'll work. To be clear, ultimately you'll want a seed job any way. The `rest` runner is more of a development-time convenience, but I would certainly not suggest it as a way of managing job-dsl scripts properly.

**Comment by iRobertas** [comment]
Thanks for info :). I use seed job to create all my jobs, but it's pain in the a... when you working on some new job and have to git push, wait for seed to run and check for errors. But at this point it's not big deal, I'll just comment envInjectBuilder part and run it with rest runner if everything work as expected I'll uncomment envInjectBuilder and push to git.
Thanks again for your time.
